# Generated by Django 4.2 on 2024-11-19 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('msystatistics', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('author_phone', models.CharField(max_length=200)),
                ('issuance_date', models.DateField(verbose_name='تاریخ صدور پروانه')),
                ('expire_date', models.DateField(verbose_name='تاریخ انقضا پروانه')),
                ('area', models.IntegerField(verbose_name='مساحت')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msystatistics.city')),
                ('proprietorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msystatistics.propertyownership')),
            ],
        ),
    ]
